name: ldm
channels:
  - nvidia
  - pytorch
  - defaults
  - pytorch-nightly
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.4
  - numpy=1.23.1
  - pip:
    - https://download.pytorch.org/whl/nightly/torchtriton-2.0.0%2B0d7e753227-cp38-cp38-linux_x86_64.whl
    - https://download.pytorch.org/whl/nightly/cu117/torch-2.0.0.dev20230102%2Bcu117-cp38-cp38-linux_x86_64.whl
    - https://download.pytorch.org/whl/nightly/cu117/torchvision-0.15.0.dev20230102%2Bcu117-cp38-cp38-linux_x86_64.whl
    - albumentations==1.3.0
    - opencv-python==4.6.0.66
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit==1.12.1
    - einops==0.3.0
    - transformers==4.19.2
    - webdataset==0.2.5
    - kornia==0.6
    - open_clip_torch==2.0.2
    - invisible-watermark>=0.1.5
    - streamlit-drawable-canvas==0.8.0
    - torchmetrics==0.6.0
    - -e .
